steps:
  # Installera beroenden med npm
  - name: 'node:20'
    entrypoint: 'npm'
    args: ['install']

  # Kör tester (valfritt)
  - name: 'node:20'
    entrypoint: 'npm'
    args: ['test']

  # Deploya till Google App Engine
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args: ['app', 'deploy', '--quiet']

# Anger vilka avbildningar som kommer att genereras
images:
  - 'gcr.io/$PROJECT_ID/my-app'
