steps:
  # Installera beroenden med npm
  - name: 'node:14'
    entrypoint: 'npm'
    args: ['install']

  # (Valfritt) Kör tester om det finns
  - name: 'node:14'
    entrypoint: 'npm'
    args: ['test']

  # Deploya till Google App Engine
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args: ['app', 'deploy', '--quiet']

# Om du vill bygga en containerbild, kan du lägga till en images-sektion
images:
  - 'gcr.io/$PROJECT_ID/my-app'

