steps:
  # Steg 1: Installera Node.js-beroenden
  - name: 'node:20'  # Använd Node.js-versionen som matchar din applikation
    entrypoint: 'npm'
    args: ['install']

  # (Valfritt) Steg 2: Kör tester om du har några tester definierade
  - name: 'node:20'
    entrypoint: 'npm'
    args: ['test']

  # Steg 3: Bygg Docker-avbildningen och tagga den
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/lunar-abbey-353913/my-node-app', '.']

  # Steg 4: Skicka Docker-avbildningen till Google Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/lunar-abbey-353913/my-node-app']

  # Steg 5: Deploya Docker-avbildningen till Google Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    args: ['run', 'deploy', 'my-node-app', '--image', 'gcr.io/lunar-abbey-353913/my-node-app', '--platform', 'managed', '--region', 'us-central1']

# Definiera de bilder som byggs
images:
  - 'gcr.io/lunar-abbey-353913/my-node-app'

